# Generated by Django 4.0.1 on 2022-07-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='hospital_name')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('donor_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='donor_id')),
                ('blood_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='blood_type')),
                ('birthdate', models.CharField(blank=True, max_length=255, null=True, verbose_name='birthdate')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
