# Generated by Django 4.0.1 on 2022-10-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='birthdate',
        ),
    ]
