# Generated by Django 4.0.1 on 2022-11-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='chat_user_id'),
        ),
    ]
