# Generated by Django 4.0.1 on 2022-12-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_assessed',
            field=models.BooleanField(default=True, verbose_name='is_assessed'),
        ),
    ]
