# Generated by Django 4.0.1 on 2022-11-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='user_id')),
                ('hospital_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='hospital_id')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
