# Generated by Django 4.0.1 on 2022-10-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0.0, verbose_name='user_id')),
                ('is_q1', models.BooleanField(default=True, verbose_name='is_q1')),
                ('is_q2', models.BooleanField(default=True, verbose_name='is_q2')),
                ('is_q3', models.BooleanField(default=True, verbose_name='is_q3')),
                ('is_q4', models.BooleanField(default=True, verbose_name='is_q4')),
                ('is_q5', models.BooleanField(default=True, verbose_name='is_q5')),
                ('is_q6', models.BooleanField(default=True, verbose_name='is_q6')),
                ('is_q7', models.BooleanField(default=True, verbose_name='is_q7')),
                ('is_q8', models.BooleanField(default=True, verbose_name='is_q8')),
                ('is_q9', models.BooleanField(default=True, verbose_name='is_q9')),
                ('is_q10', models.BooleanField(default=True, verbose_name='is_q10')),
                ('is_q11', models.BooleanField(default=True, verbose_name='is_q11')),
                ('is_q12', models.BooleanField(default=True, verbose_name='is_q12')),
                ('is_q13', models.BooleanField(default=True, verbose_name='is_q13')),
                ('is_q14', models.BooleanField(default=True, verbose_name='is_q14')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
