# Generated by Django 4.0.1 on 2022-10-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assestment', '0002_alter_assestment_is_q1_alter_assestment_is_q10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assestment',
            name='hospital_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='hospital_id'),
        ),
    ]
