# Generated by Django 4.0.1 on 2022-10-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assestment', '0004_remove_assestment_is_q14'),
    ]

    operations = [
        migrations.AddField(
            model_name='assestment',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='status'),
        ),
    ]
