# Generated by Django 4.0.1 on 2022-12-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assestment', '0005_assestment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assestment',
            name='is_q14',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q14'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q15',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q15'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q16',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q16'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q17',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q17'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q18',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q18'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q19',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q19'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q20',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q20'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q21',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q21'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q22',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q22'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q23',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q23'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q24',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q24'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q25',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q25'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q26',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q26'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q27',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q27'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q28',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q28'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q29',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q29'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q30',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q30'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q31',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q31'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q32',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q32'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q33',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q33'),
        ),
        migrations.AddField(
            model_name='assestment',
            name='is_q34',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_q34'),
        ),
    ]
