# Generated by Django 4.0.1 on 2022-12-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='hospital_name')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='longitude')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='latitude')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
